### ISSUE TITLE
Broken url?

### ISSUE THREAD

**Issue by msmahliss** [jonathanong/heroku-buildpack-ffmpeg#1]
Been using this repo for ffmpeg builds on heroku. Been working great, but seems the download url is now broken. Here's the output from the heroku build.

remote: =====> Downloading Buildpack: https://github.com/jonathanong/heroku-buildpack-ffmpeg.git
remote: =====> Detected Framework: ffmpeg
remote: -----> Install ffmpeg
remote:        DOWNLOAD_URL =  http://ffmpeg.gusari.org/static/64bit/ffmpeg.static.64bit.latest.tar.gz
remote:
remote: gzip: stdin: unexpected end of file
remote: tar: Child returned status 1

**Comment by jonathanong** [comment]
use this: https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest
